name: localstorage
description: Simple json file-based storage fo flutter. Alternative to react-native AsyncStorage
version: 3.0.2+15
author: Andrei Lesnitsky <andrei.lesnitsky@gmail.com>
homepage: https://github.com/lesnitsky/flutter_localstorage

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
